import { useState, useEffect } from "react";
import API from "../../api";

const CLASSES = [" 1", " 2", " 3",];
const DIVISIONS = ["A", "B", "C"];
const SUBJECTS = ["English", "Maths", "Science",];

export default function StudentForm({ initialData = {}, onClose, onSubmit }) {
  // Initialize form with proper structure
  const [formData, setFormData] = useState({
    user_code: initialData.user_code || "",
    admission_no: initialData.admission_no || "",
    name: initialData.name || "",
    email: initialData.email || "",
    password: initialData.password || "",
    phone_no: initialData.phone_no || "", // Added phone number
    address: initialData.address || "", // Added address
    class: initialData.class || "",
    division: initialData.division || "",
    gender: initialData.gender || "M",
    parent_name: initialData.parent_name || "",
    parent_email: initialData.parent_email || "",
    subjects: initialData.subjects || [],
    academic_year: initialData.academic_year || "2024-25"
  });

  const [message, setMessage] = useState(""); // Add message state
  const [loading, setLoading] = useState(false); // Add loading state
  const [phoneError, setPhoneError] = useState(""); // Phone validation error

  // Validate phone number format
  const validatePhoneNumber = (phone) => {
    if (!phone) return true; // Allow empty (since allowNull: true)

    // Check if phone is exactly 10 digits
    const phoneRegex = /^\d{10}$/;
    if (!phoneRegex.test(phone)) {
      setPhoneError("Phone number must be exactly 10 digits");
      return false;
    }

    setPhoneError("");
    return true;
  };

  const handleSubmit = async (e) => { // Make this async
    e.preventDefault();

    // Validate required fields
    if (!formData.name || !formData.name.trim()) {
      setMessage("Student name is required");
      return;
    }

    if (!formData.class || !formData.division) {
      setMessage("Class and Division are required");
      return;
    }

    if (!formData.subjects || formData.subjects.length === 0) {
      setMessage("Please select at least one subject");
      return;
    }

    // Validate phone number if provided
    if (formData.phone_no && !validatePhoneNumber(formData.phone_no)) {
      setMessage("Please correct phone number format");
      return;
    }

    // Validate academic year format
    const yearRegex = /^\d{4}-\d{2}$/;
    if (!yearRegex.test(formData.academic_year)) {
      setMessage("Academic Year must be in format YYYY-YY (e.g., 2024-25)");
      return;
    }

    setLoading(true);
    setMessage("");

    try {
      // Call the API directly
      const response = await API.post("/api/users/create", {
        name: formData.name.trim(),
        email: formData.email?.trim() || null,
        password: formData.password || null, // Let backend generate if empty
        phone_no: formData.phone_no?.trim() || null, // Added phone_no
        address: formData.address?.trim() || null, // Added address
        gender: formData.gender,
        class: formData.class,
        division: formData.division,
        academic_year: formData.academic_year,
        subjects: formData.subjects,
        parent_name: formData.parent_name?.trim() || null,
        parent_email: formData.parent_email?.trim() || null
      });

      if (response.data.success) {
        setMessage(`✅ Student created successfully! 
          User Code: ${response.data.student?.usercode || 'Generated by system'}
          Admission No: ${response.data.student?.admission_no || 'Generated by system'}`);

        // If parent component provided onSubmit callback, call it
        if (onSubmit) {
          onSubmit(formData);
        }

        // Reset form after successful submission
        setTimeout(() => {
          setFormData({
            user_code: "",
            admission_no: "",
            name: "",
            email: "",
            password: "",
            phone_no: "", // Reset phone
            address: "", // Reset address
            class: "",
            division: "",
            gender: "M",
            parent_name: "",
            parent_email: "",
            subjects: [],
            academic_year: "2024-25"
          });
          setMessage("");
          if (onClose) onClose();
        }, 3000);
      } else {
        setMessage(response.data.error || "Failed to create student");
      }
    } catch (err) {
      console.error("Error creating student:", err);
      setMessage(err.response?.data?.error || "Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleSubjectChange = (subject) => {
    const updatedSubjects = formData.subjects.includes(subject)
      ? formData.subjects.filter(s => s !== subject)
      : [...formData.subjects, subject];

    setFormData({
      ...formData,
      subjects: updatedSubjects
    });
  };

  const handleInputChange = (field, value) => {
    // Phone number validation on change
    if (field === 'phone_no') {
      // Remove non-digit characters
      const digitsOnly = value.replace(/\D/g, '');
      // Limit to 10 digits
      const limitedDigits = digitsOnly.slice(0, 10);

      setFormData({
        ...formData,
        [field]: limitedDigits
      });

      // Validate phone number format
      if (limitedDigits && limitedDigits.length !== 10) {
        setPhoneError("Phone number must be exactly 10 digits");
      } else {
        setPhoneError("");
      }
    } else {
      setFormData({
        ...formData,
        [field]: value
      });
    }

    // Clear general message when user starts typing
    if (message) setMessage("");
  };

  const handleCancel = () => {
    // Reset all form fields
    setFormData({
      user_code: "",
      admission_no: "",
      name: "",
      email: "",
      password: "",
      phone_no: "", // Reset phone
      address: "", // Reset address
      class: "",
      division: "",
      gender: "M",
      parent_name: "",
      parent_email: "",
      subjects: [],
      academic_year: "2024-25"
    });
    setMessage("");
    setPhoneError("");
    // Close the form if onClose prop is passed and it was meant to close a modal
    if (onClose) onClose();
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Message Display */}
      {message && (
        <div className={`p-4 rounded-xl ${message.includes("✅") ? 'bg-green-50 text-green-800 border border-green-200' : 'bg-red-50 text-red-800 border border-red-200'}`}>
          {message.split('\n').map((line, i) => (
            <span key={i}>
              {line}
              <br />
            </span>
          ))}
        </div>
      )}

      {/* ... rest of the form fields ... */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* User Code - Show placeholder since backend generates it */}
        <div className="input-group">
          <label>User Code</label>
          <div className="flex items-center">
            <input
              type="text"
              value="Auto-generated by system"
              readOnly
              className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-gray-500 cursor-not-allowed"
            />
            <span className="ml-2 px-2 py-1 text-xs bg-blue-100 text-blue-800 rounded-lg">
              Auto
            </span>
          </div>
          <p className="text-xs text-gray-500 mt-1">
            Will be assigned as STU-0001, STU-0002, etc.
          </p>
        </div>

        {/* Admission No - Show placeholder since backend generates it */}
        <div className="input-group">
          <label>Admission No</label>
          <div className="flex items-center">
            <input
              type="text"
              value="Auto-generated by system"
              readOnly
              className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-gray-500 cursor-not-allowed"
            />
            <span className="ml-2 px-2 py-1 text-xs bg-green-100 text-green-800 rounded-lg">
              Auto
            </span>
          </div>
          <p className="text-xs text-gray-500 mt-1">
            Will be assigned as ADM0001, ADM0002, etc.
          </p>
        </div>

        {/* Full Name - Required */}
        <div className="input-group">
          <label>Full Name *</label>
          <input
            type="text"
            required
            value={formData.name}
            onChange={(e) => handleInputChange("name", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="Enter student name"
          />
        </div>

        {/* Gender - Required */}
        <div className="input-group">
          <label>Gender *</label>
          <select
            value={formData.gender}
            onChange={(e) => handleInputChange("gender", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
          >
            <option value="M">Male</option>
            <option value="F">Female</option>
            <option value="O">Other</option>
          </select>
        </div>

        {/* Email */}
        <div className="input-group">
          <label>Email</label>
          <input
            type="email"
            value={formData.email}
            onChange={(e) => handleInputChange("email", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="student@example.com"
          />
        </div>

        {/* Password */}
        <div className="input-group">
          <label>Password</label>
          <input
            type="password"
            value={formData.password}
            onChange={(e) => handleInputChange("password", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="Leave blank for auto-generation"
          />
          <p className="text-xs text-gray-500 mt-1">
            Leave blank to generate random password
          </p>
        </div>

        {/* Phone Number */}
        <div className="input-group">
          <label>Phone Number</label>
          <input
            type="tel"
            value={formData.phone_no}
            onChange={(e) => handleInputChange("phone_no", e.target.value)}
            className={`w-full px-4 py-2.5 border rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition ${phoneError ? 'border-red-300' : 'border-gray-200'
              }`}
            placeholder="Enter 10-digit phone number"
            maxLength="10"
          />
          {phoneError && (
            <p className="text-xs text-red-500 mt-1">{phoneError}</p>
          )}
          <p className="text-xs text-gray-500 mt-1">
            Enter exactly 10 digits (optional)
          </p>
        </div>

        {/* Address */}
        <div className="input-group md:col-span-2">
          <label>Address</label>
          <textarea
            value={formData.address}
            onChange={(e) => handleInputChange("address", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition resize-none"
            placeholder="Enter student address"
            rows="3"
          />
          <p className="text-xs text-gray-500 mt-1">
            Full address (optional)
          </p>
        </div>

        {/* Class - Required */}
        <div className="input-group">
          <label>Class *</label>
          <select
            value={formData.class}
            onChange={(e) => handleInputChange("class", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            required
          >
            <option value="">Select Class</option>
            {CLASSES.map((cls) => (
              <option key={cls} value={cls}>{cls}</option>
            ))}
          </select>
        </div>

        {/* Division - Required */}
        <div className="input-group">
          <label>Division *</label>
          <select
            value={formData.division}
            onChange={(e) => handleInputChange("division", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            required
          >
            <option value="">Select Division</option>
            {DIVISIONS.map((div) => (
              <option key={div} value={div}>{div}</option>
            ))}
          </select>
        </div>

        {/* Parent Name */}
        <div className="input-group">
          <label>Parent Name</label>
          <input
            type="text"
            value={formData.parent_name}
            onChange={(e) => handleInputChange("parent_name", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="Parent/Guardian name"
          />
        </div>

        {/* Parent Email */}
        <div className="input-group">
          <label>Parent Email</label>
          <input
            type="email"
            value={formData.parent_email}
            onChange={(e) => handleInputChange("parent_email", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="parent@example.com"
          />
        </div>
      </div>

      {/* Subjects Selection - Multiple */}
      <div className="input-group pt-2">
        <label>Select Subjects * (Choose at least one)</label>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3 p-4 bg-gray-50 rounded-xl">
          {SUBJECTS.map((subject) => (
            <div key={subject} className="flex items-center">
              <input
                type="checkbox"
                id={`subject-${subject}`}
                checked={formData.subjects.includes(subject)}
                onChange={() => handleSubjectChange(subject)}
                className="h-5 w-5 text-purple-600 rounded focus:ring-purple-500"
              />
              <label
                htmlFor={`subject-${subject}`}
                className="ml-3 text-sm font-medium text-gray-700 cursor-pointer"
              >
                {subject}
              </label>
            </div>
          ))}
        </div>
        {formData.subjects.length > 0 && (
          <div className="mt-3">
            <p className="text-sm text-gray-600">
              Selected: <span className="font-semibold text-purple-600">
                {formData.subjects.join(", ")}
              </span>
            </p>
          </div>
        )}
      </div>

      {/* Academic Year */}
      <div className="input-group">
        <label>Academic Year *</label>
        <input
          type="text"
          value={formData.academic_year}
          onChange={(e) => handleInputChange("academic_year", e.target.value)}
          className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
          placeholder="2024-25"
          required
        />
        <p className="text-xs text-gray-500 mt-1">
          Format: YYYY-YY (e.g., 2024-25)
        </p>
      </div>

      {/* Action Buttons */}
      <div className="form-actions">
        <button
          type="button"
          onClick={handleCancel}
          className="cancel-btn"
          disabled={loading}
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={loading}
        >
          {loading ? "Creating..." : (initialData.admission_no ? "Update Student" : "Create Student")}
        </button>
      </div>
    </form>
  );
}