import { useState, useEffect } from "react";
import API from "../../api"; // Import your API instance

const SUBJECTS = ["Maths", "Physics", "Chemistry", "Biology"];
const CLASSES = ["Class 7", "Class 8", "Class 9", "Class 10"];
const BATCHES = ["A", "B", "C"];
const GENDERS = [
  { value: "M", label: "Male" },
  { value: "F", label: "Female" },
  { value: "O", label: "Other" }
];

export default function TeacherForm({ initialData = {}, onClose, onSubmit }) {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    password: "",
    gender: "",
    phone_no: "",
    address: "",
    endorsements: [],
    academic_year: ""
  });

  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState({ type: "", text: "" });

  // Set current academic year on mount
  useEffect(() => {
    const currentYear = new Date().getFullYear();
    const nextYear = currentYear + 1;
    setFormData(prev => ({
      ...prev,
      academic_year: `${currentYear}-${nextYear}`
    }));
  }, []);

  // Add a new empty endorsement row
  const addEndorsement = () => {
    setFormData(prev => ({
      ...prev,
      endorsements: [
        ...prev.endorsements,
        { class: "", batch: "", subjects: [] }
      ]
    }));
  };

  const removeEndorsement = (index) => {
    setFormData(prev => ({
      ...prev,
      endorsements: prev.endorsements.filter((_, i) => i !== index)
    }));
  };

  // Update class or batch
  const updateEndorsement = (index, key, value) => {
    const updatedEndorsements = [...formData.endorsements];
    updatedEndorsements[index][key] = value;

    setFormData(prev => ({
      ...prev,
      endorsements: updatedEndorsements
    }));
  };

  // Toggle subject in endorsement row
  const toggleSubject = (index, subject) => {
    const updatedEndorsements = [...formData.endorsements];
    updatedEndorsements[index].subjects =
      updatedEndorsements[index].subjects.includes(subject)
        ? updatedEndorsements[index].subjects.filter((s) => s !== subject)
        : [...updatedEndorsements[index].subjects, subject];

    setFormData(prev => ({
      ...prev,
      endorsements: updatedEndorsements
    }));
  };

  const canAddMore = () => {
    if (formData.endorsements.length === 0) return true;

    const last = formData.endorsements[formData.endorsements.length - 1];
    return last.class && last.batch && last.subjects.length > 0;
  };

  // Handle form input changes
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  // Validate form
  const validateForm = () => {
    if (!formData.name || !formData.email || !formData.password || !formData.gender) {
      setMessage({ type: "error", text: "Name, email, password, and gender are required" });
      return false;
    }

    // Email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(formData.email)) {
      setMessage({ type: "error", text: "Invalid email format" });
      return false;
    }

    // Password validation
    if (formData.password.length < 6) {
      setMessage({ type: "error", text: "Password must be at least 6 characters long" });
      return false;
    }

    // Validate endorsements
    for (const endorsement of formData.endorsements) {
      if (!endorsement.class || !endorsement.batch) {
        setMessage({ type: "error", text: "Each endorsement must have class and batch" });
        return false;
      }

      if (!Array.isArray(endorsement.subjects) || endorsement.subjects.length === 0) {
        setMessage({ type: "error", text: "Each endorsement must have at least one subject" });
        return false;
      }
    }

    return true;
  };

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setMessage({ type: "", text: "" });

    if (!validateForm()) {
      return;
    }

    setLoading(true);

    try {
      const response = await API.post("/api/teachers/register", {
        name: formData.name.trim(),
        email: formData.email.trim(),
        password: formData.password,
        gender: formData.gender,
        phone_no: formData.phone_no,
        address: formData.address,
        endorsements: formData.endorsements,
        academic_year: formData.academic_year,
        created_by: "admin"
      });

      const result = await response.data;

      if (result.success) {
        const userCode = result.data?.teacher?.usercode || "Generated by system";
        setMessage({
          type: "success",
          text: `✅ Teacher registered successfully!\nUser Code: ${userCode}`
        });

        if (onSubmit) {
          onSubmit(formData);
        }

        setTimeout(() => {
          setFormData({
            name: "",
            email: "",
            password: "",
            gender: "M",
            phone_no: "",
            address: "",
            endorsements: [],
            academic_year: formData.academic_year
          });
          setMessage({ type: "", text: "" });
          if (onClose) onClose();
        }, 3000);
      } else {
        setMessage({
          type: "error",
          text: result.message || "Registration failed"
        });
      }
    } catch (error) {
      console.error("Registration error:", error);
      setMessage({
        type: "error",
        text: error.response?.data?.message || "Network error. Please try again."
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Message Display */}
      {message.text && (
        <div className={`p-4 rounded-xl ${message.type === "success" ? 'bg-green-50 text-green-800 border border-green-200' : 'bg-red-50 text-red-800 border border-red-200'}`}>
          {message.text.split('\n').map((line, i) => (
            <span key={i}>
              {line}
              <br />
            </span>
          ))}
        </div>
      )}

      {/* BASIC DETAILS */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* User Code - Show placeholder since backend generates it */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            User Code
          </label>
          <div className="flex items-center">
            <input
              type="text"
              value="Auto-generated by system"
              readOnly
              className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-gray-500 cursor-not-allowed"
            />
            <span className="ml-2 px-2 py-1 text-xs bg-blue-100 text-blue-800 rounded-lg">
              Auto
            </span>
          </div>
          <p className="text-xs text-gray-500 mt-1">
            Will be assigned as TEA-0001, TEA-0002, etc.
          </p>
        </div>

        {/* Full Name * */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Full Name *
          </label>
          <input
            name="name"
            value={formData.name}
            onChange={handleInputChange}
            required
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="Enter your full name"
          />
        </div>

        {/* Email * */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Email *
          </label>
          <input
            type="email"
            name="email"
            value={formData.email}
            onChange={handleInputChange}
            required
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="Enter your email"
          />
        </div>

        {/* Password * */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Password *
          </label>
          <input
            type="password"
            name="password"
            value={formData.password}
            onChange={handleInputChange}
            minLength="6"
            required
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="Enter your password"
          />
        </div>

        {/* Gender * */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Gender *
          </label>
          <select
            name="gender"
            value={formData.gender}
            onChange={handleInputChange}
            required
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
          >
            {GENDERS.map((gender) => (
              <option key={gender.value} value={gender.value}>
                {gender.label}
              </option>
            ))}
          </select>
        </div>

        {/* Academic Year */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Academic Year *
          </label>
          <input
            name="academic_year"
            value={formData.academic_year}
            onChange={handleInputChange}
            required
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="2024-2025"
          />
          <p className="text-xs text-gray-500 mt-1">
            Format: YYYY-YY (e.g., 2024-25)
          </p>
        </div>

        {/* Phone Number */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Phone Number
          </label>
          <input
            name="phone_no"
            value={formData.phone_no}
            onChange={handleInputChange}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="Enter phone number"
          />
        </div>

        {/* Address */}
        <div className="input-group md:col-span-2">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Address
          </label>
          <textarea
            name="address"
            value={formData.address}
            onChange={handleInputChange}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition resize-none"
            placeholder="Enter full address"
            rows="3"
          />
        </div>
      </div>

      {/* ENDORSEMENTS SECTION - MATCHING YOUR ORIGINAL UI */}
      <div className="teacher-section">
        <div className="section-header">
          <h4 className="text-lg font-medium text-gray-800 mb-1">
            Class / Batch / Subject Endorsements
          </h4>
          <button
            type="button"
            className="add-btn"
            onClick={addEndorsement}
            disabled={!canAddMore()}
            style={{
              opacity: canAddMore() ? 1 : 0.5,
              cursor: canAddMore() ? "pointer" : "not-allowed",
              background: '#562dbd',
              color: 'white',
              border: 'none',
              padding: '0.5rem 1rem',
              borderRadius: '4px',
              fontSize: '0.9rem'
            }}
          >
            ＋ Add Endorsements
          </button>
        </div>

        {formData.endorsements.map((row, i) => (
          <div key={i} className="endorsement-row" style={{
            display: 'flex',
            alignItems: 'center',
            gap: '1rem',
            padding: '1rem',
            border: '1px solid #eee',
            borderRadius: '6px',
            marginBottom: '1rem',
            background: '#f9f9f9',
            flexWrap: 'wrap'
          }}>
            {/* REMOVE BUTTON */}
            <button
              type="button"
              className="remove-btn"
              onClick={() => removeEndorsement(i)}
              title="Remove endorsement"
              style={{
                background: '#ff4444',
                color: 'white',
                border: 'none',
                width: '30px',
                height: '30px',
                borderRadius: '50%',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                cursor: 'pointer',
                fontSize: '1.2rem'
              }}
            >
              −
            </button>

            {/* Class */}
            <select
              value={row.class}
              onChange={(e) => updateEndorsement(i, "class", e.target.value)}
              style={{
                padding: '0.5rem',
                border: '1px solid #ddd',
                borderRadius: '4px',
                minWidth: '120px'
              }}
            >
              <option value="">Class</option>
              {CLASSES.map((c) => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>

            {/* Batch */}
            <select
              value={row.batch}
              onChange={(e) => updateEndorsement(i, "batch", e.target.value)}
              style={{
                padding: '0.5rem',
                border: '1px solid #ddd',
                borderRadius: '4px',
                minWidth: '80px'
              }}
            >
              <option value="">Batch</option>
              {BATCHES.map((b) => (
                <option key={b} value={b}>{b}</option>
              ))}
            </select>

            {/* Subjects (Checkboxes) - Inline as per your original design */}
            <div className="checkbox-group inline" style={{
              display: 'flex',
              gap: '1rem',
              flexWrap: 'wrap',
              marginLeft: '1rem'
            }}>
              {SUBJECTS.map((sub) => (
                <label key={sub} className="checkbox-item" style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                  cursor: 'pointer'
                }}>
                  <input
                    type="checkbox"
                    checked={row.subjects.includes(sub)}
                    onChange={() => toggleSubject(i, sub)}
                    style={{
                      width: '18px',
                      height: '18px',
                      cursor: 'pointer'
                    }}
                  />
                  <span style={{ fontSize: '0.9rem' }}>{sub}</span>
                </label>
              ))}
            </div>
          </div>
        ))}

        {formData.endorsements.length === 0 && (
          <div className="no-endorsements" style={{
            textAlign: 'center',
            padding: '2rem',
            color: '#999',
            border: '2px dashed #ddd',
            borderRadius: '6px',
            marginTop: '1rem'
          }}>
            No endorsements added. Click "Add Endorsement" to add class/batch/subject assignments.
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="flex gap-4 pt-6 border-t">
        {onClose && (
          <button
            type="button"
            onClick={onClose}
            className="flex-1 px-6 py-3.5 border border-gray-300 text-gray-700 rounded-xl hover:bg-gray-50 transition-all duration-200 font-medium"
            disabled={loading}
          >
            Cancel
          </button>
        )}
        <button
          type="submit"
          className={`flex-1 px-6 py-3.5 ${onClose
            ? 'bg-gradient-to-r from-purple-600 to-indigo-600'
            : 'bg-purple-600'
            } text-white rounded-xl hover:shadow-lg hover:scale-[1.02] transition-all duration-200 font-semibold disabled:opacity-70 disabled:cursor-not-allowed`}
          disabled={loading}
        >
          {loading ? "Creating..." : "Create Teacher"}
        </button>
      </div>
    </form>
  );
}